"""
Sample data for AquaSDG - 50+ regions across Sub-Saharan Africa, South Asia, and Southeast Asia
"""

REGIONS_DATA = [
    # ==================== SUB-SAHARAN AFRICA ====================
    # Kenya
    {
        "id": "ke-turkana",
        "name": "Turkana County",
        "country": "Kenya",
        "region_type": "Arid/Semi-arid",
        "coordinates": {"lat": 3.3122, "lng": 35.5657},
        "population": 926976,
        "water_access": {
            "safely_managed_pct": 12.5,
            "basic_pct": 28.3,
            "limited_pct": 18.2,
            "unimproved_pct": 25.1,
            "surface_water_pct": 15.9
        },
        "water_stress_index": 0.85,
        "flood_risk_score": 0.15,
        "drought_risk_score": 0.92,
        "climate_vulnerability": 0.88,
        "infrastructure_gap": 0.78,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 250,
        "near_water_body": False,
        "coastal": False,
        "population_density": 15
    },
    {
        "id": "ke-marsabit",
        "name": "Marsabit County",
        "country": "Kenya",
        "region_type": "Arid",
        "coordinates": {"lat": 2.3367, "lng": 37.9908},
        "population": 459785,
        "water_access": {
            "safely_managed_pct": 8.2,
            "basic_pct": 22.1,
            "limited_pct": 20.5,
            "unimproved_pct": 32.4,
            "surface_water_pct": 16.8
        },
        "water_stress_index": 0.82,
        "flood_risk_score": 0.08,
        "drought_risk_score": 0.95,
        "climate_vulnerability": 0.91,
        "infrastructure_gap": 0.85,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 200,
        "near_water_body": False,
        "coastal": False,
        "population_density": 4
    },
    {
        "id": "ke-mombasa",
        "name": "Mombasa County",
        "country": "Kenya",
        "region_type": "Urban Coastal",
        "coordinates": {"lat": -4.0435, "lng": 39.6682},
        "population": 1203331,
        "water_access": {
            "safely_managed_pct": 45.2,
            "basic_pct": 35.8,
            "limited_pct": 10.2,
            "unimproved_pct": 6.3,
            "surface_water_pct": 2.5
        },
        "water_stress_index": 0.55,
        "flood_risk_score": 0.65,
        "drought_risk_score": 0.35,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.32,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 1050,
        "near_water_body": True,
        "coastal": True,
        "population_density": 4520
    },
    {
        "id": "ke-kisumu",
        "name": "Kisumu County",
        "country": "Kenya",
        "region_type": "Lakeside",
        "coordinates": {"lat": -0.1022, "lng": 34.7617},
        "population": 1168569,
        "water_access": {
            "safely_managed_pct": 32.5,
            "basic_pct": 38.2,
            "limited_pct": 12.8,
            "unimproved_pct": 11.5,
            "surface_water_pct": 5.0
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.58,
        "drought_risk_score": 0.25,
        "climate_vulnerability": 0.48,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1200,
        "near_water_body": True,
        "coastal": False,
        "population_density": 520
    },
    {
        "id": "ke-kitui",
        "name": "Kitui County",
        "country": "Kenya",
        "region_type": "Semi-arid",
        "coordinates": {"lat": -1.3667, "lng": 38.0167},
        "population": 1130129,
        "water_access": {
            "safely_managed_pct": 18.5,
            "basic_pct": 32.1,
            "limited_pct": 22.3,
            "unimproved_pct": 18.2,
            "surface_water_pct": 8.9
        },
        "water_stress_index": 0.68,
        "flood_risk_score": 0.25,
        "drought_risk_score": 0.72,
        "climate_vulnerability": 0.65,
        "infrastructure_gap": 0.55,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 500,
        "near_water_body": False,
        "coastal": False,
        "population_density": 38
    },

    # Ethiopia
    {
        "id": "et-afar",
        "name": "Afar Region",
        "country": "Ethiopia",
        "region_type": "Arid",
        "coordinates": {"lat": 12.0, "lng": 41.0},
        "population": 1890815,
        "water_access": {
            "safely_managed_pct": 6.2,
            "basic_pct": 18.5,
            "limited_pct": 15.3,
            "unimproved_pct": 35.2,
            "surface_water_pct": 24.8
        },
        "water_stress_index": 0.92,
        "flood_risk_score": 0.12,
        "drought_risk_score": 0.98,
        "climate_vulnerability": 0.95,
        "infrastructure_gap": 0.92,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 150,
        "near_water_body": False,
        "coastal": False,
        "population_density": 18
    },
    {
        "id": "et-somali",
        "name": "Somali Region",
        "country": "Ethiopia",
        "region_type": "Arid",
        "coordinates": {"lat": 6.0, "lng": 43.0},
        "population": 5445563,
        "water_access": {
            "safely_managed_pct": 8.5,
            "basic_pct": 22.3,
            "limited_pct": 18.2,
            "unimproved_pct": 28.5,
            "surface_water_pct": 22.5
        },
        "water_stress_index": 0.88,
        "flood_risk_score": 0.18,
        "drought_risk_score": 0.92,
        "climate_vulnerability": 0.89,
        "infrastructure_gap": 0.85,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 300,
        "near_water_body": False,
        "coastal": False,
        "population_density": 15
    },
    {
        "id": "et-oromia",
        "name": "Oromia Region",
        "country": "Ethiopia",
        "region_type": "Mixed",
        "coordinates": {"lat": 8.0, "lng": 39.0},
        "population": 35001652,
        "water_access": {
            "safely_managed_pct": 22.5,
            "basic_pct": 35.8,
            "limited_pct": 18.5,
            "unimproved_pct": 15.2,
            "surface_water_pct": 8.0
        },
        "water_stress_index": 0.55,
        "flood_risk_score": 0.35,
        "drought_risk_score": 0.52,
        "climate_vulnerability": 0.58,
        "infrastructure_gap": 0.48,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 800,
        "near_water_body": False,
        "coastal": False,
        "population_density": 102
    },
    {
        "id": "et-addis",
        "name": "Addis Ababa",
        "country": "Ethiopia",
        "region_type": "Urban",
        "coordinates": {"lat": 9.0320, "lng": 38.7469},
        "population": 3437981,
        "water_access": {
            "safely_managed_pct": 52.3,
            "basic_pct": 32.5,
            "limited_pct": 8.2,
            "unimproved_pct": 4.5,
            "surface_water_pct": 2.5
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.25,
        "drought_risk_score": 0.35,
        "climate_vulnerability": 0.38,
        "infrastructure_gap": 0.28,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 1200,
        "near_water_body": False,
        "coastal": False,
        "population_density": 5300
    },
    {
        "id": "et-amhara",
        "name": "Amhara Region",
        "country": "Ethiopia",
        "region_type": "Highland",
        "coordinates": {"lat": 11.5, "lng": 38.0},
        "population": 21412269,
        "water_access": {
            "safely_managed_pct": 15.8,
            "basic_pct": 32.5,
            "limited_pct": 22.3,
            "unimproved_pct": 18.5,
            "surface_water_pct": 10.9
        },
        "water_stress_index": 0.48,
        "flood_risk_score": 0.42,
        "drought_risk_score": 0.48,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.52,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1000,
        "near_water_body": False,
        "coastal": False,
        "population_density": 108
    },

    # Nigeria
    {
        "id": "ng-borno",
        "name": "Borno State",
        "country": "Nigeria",
        "region_type": "Semi-arid",
        "coordinates": {"lat": 11.5, "lng": 13.0},
        "population": 5891582,
        "water_access": {
            "safely_managed_pct": 12.5,
            "basic_pct": 25.8,
            "limited_pct": 20.5,
            "unimproved_pct": 25.2,
            "surface_water_pct": 16.0
        },
        "water_stress_index": 0.72,
        "flood_risk_score": 0.22,
        "drought_risk_score": 0.65,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.78,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 450,
        "near_water_body": True,
        "coastal": False,
        "population_density": 75
    },
    {
        "id": "ng-lagos",
        "name": "Lagos State",
        "country": "Nigeria",
        "region_type": "Urban Coastal",
        "coordinates": {"lat": 6.5244, "lng": 3.3792},
        "population": 15946251,
        "water_access": {
            "safely_managed_pct": 38.5,
            "basic_pct": 35.2,
            "limited_pct": 12.5,
            "unimproved_pct": 8.8,
            "surface_water_pct": 5.0
        },
        "water_stress_index": 0.58,
        "flood_risk_score": 0.75,
        "drought_risk_score": 0.15,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.35,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 1600,
        "near_water_body": True,
        "coastal": True,
        "population_density": 6871
    },
    {
        "id": "ng-kano",
        "name": "Kano State",
        "country": "Nigeria",
        "region_type": "Semi-arid",
        "coordinates": {"lat": 12.0, "lng": 8.5},
        "population": 13054891,
        "water_access": {
            "safely_managed_pct": 22.5,
            "basic_pct": 38.2,
            "limited_pct": 18.5,
            "unimproved_pct": 14.3,
            "surface_water_pct": 6.5
        },
        "water_stress_index": 0.55,
        "flood_risk_score": 0.18,
        "drought_risk_score": 0.42,
        "climate_vulnerability": 0.48,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 700,
        "near_water_body": False,
        "coastal": False,
        "population_density": 468
    },
    {
        "id": "ng-rivers",
        "name": "Rivers State",
        "country": "Nigeria",
        "region_type": "Delta",
        "coordinates": {"lat": 4.8, "lng": 7.0},
        "population": 7303992,
        "water_access": {
            "safely_managed_pct": 28.5,
            "basic_pct": 35.2,
            "limited_pct": 15.8,
            "unimproved_pct": 12.5,
            "surface_water_pct": 8.0
        },
        "water_stress_index": 0.35,
        "flood_risk_score": 0.85,
        "drought_risk_score": 0.08,
        "climate_vulnerability": 0.62,
        "infrastructure_gap": 0.45,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2500,
        "near_water_body": True,
        "coastal": True,
        "population_density": 450
    },
    {
        "id": "ng-sokoto",
        "name": "Sokoto State",
        "country": "Nigeria",
        "region_type": "Semi-arid",
        "coordinates": {"lat": 13.0, "lng": 5.25},
        "population": 4851786,
        "water_access": {
            "safely_managed_pct": 18.2,
            "basic_pct": 32.5,
            "limited_pct": 22.3,
            "unimproved_pct": 18.5,
            "surface_water_pct": 8.5
        },
        "water_stress_index": 0.65,
        "flood_risk_score": 0.15,
        "drought_risk_score": 0.55,
        "climate_vulnerability": 0.58,
        "infrastructure_gap": 0.55,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 550,
        "near_water_body": False,
        "coastal": False,
        "population_density": 175
    },

    # Mozambique
    {
        "id": "mz-cabo",
        "name": "Cabo Delgado Province",
        "country": "Mozambique",
        "region_type": "Coastal",
        "coordinates": {"lat": -12.5, "lng": 40.0},
        "population": 2350485,
        "water_access": {
            "safely_managed_pct": 15.2,
            "basic_pct": 28.5,
            "limited_pct": 22.3,
            "unimproved_pct": 22.0,
            "surface_water_pct": 12.0
        },
        "water_stress_index": 0.55,
        "flood_risk_score": 0.45,
        "drought_risk_score": 0.52,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.68,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 900,
        "near_water_body": True,
        "coastal": True,
        "population_density": 25
    },
    {
        "id": "mz-gaza",
        "name": "Gaza Province",
        "country": "Mozambique",
        "region_type": "Semi-arid",
        "coordinates": {"lat": -23.5, "lng": 33.0},
        "population": 1452523,
        "water_access": {
            "safely_managed_pct": 12.5,
            "basic_pct": 25.8,
            "limited_pct": 20.5,
            "unimproved_pct": 25.2,
            "surface_water_pct": 16.0
        },
        "water_stress_index": 0.72,
        "flood_risk_score": 0.35,
        "drought_risk_score": 0.68,
        "climate_vulnerability": 0.75,
        "infrastructure_gap": 0.72,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 450,
        "near_water_body": False,
        "coastal": False,
        "population_density": 18
    },
    {
        "id": "mz-maputo",
        "name": "Maputo Province",
        "country": "Mozambique",
        "region_type": "Urban Coastal",
        "coordinates": {"lat": -25.9, "lng": 32.6},
        "population": 2507619,
        "water_access": {
            "safely_managed_pct": 42.5,
            "basic_pct": 32.8,
            "limited_pct": 12.5,
            "unimproved_pct": 8.2,
            "surface_water_pct": 4.0
        },
        "water_stress_index": 0.48,
        "flood_risk_score": 0.42,
        "drought_risk_score": 0.35,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.38,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 850,
        "near_water_body": True,
        "coastal": True,
        "population_density": 280
    },
    {
        "id": "mz-zambezia",
        "name": "Zambezia Province",
        "country": "Mozambique",
        "region_type": "River Basin",
        "coordinates": {"lat": -17.5, "lng": 36.5},
        "population": 4063647,
        "water_access": {
            "safely_managed_pct": 22.5,
            "basic_pct": 35.2,
            "limited_pct": 18.5,
            "unimproved_pct": 15.8,
            "surface_water_pct": 8.0
        },
        "water_stress_index": 0.38,
        "flood_risk_score": 0.72,
        "drought_risk_score": 0.25,
        "climate_vulnerability": 0.58,
        "infrastructure_gap": 0.52,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1400,
        "near_water_body": True,
        "coastal": False,
        "population_density": 35
    },

    # Tanzania
    {
        "id": "tz-dodoma",
        "name": "Dodoma Region",
        "country": "Tanzania",
        "region_type": "Semi-arid",
        "coordinates": {"lat": -6.2, "lng": 35.75},
        "population": 3081485,
        "water_access": {
            "safely_managed_pct": 18.5,
            "basic_pct": 32.5,
            "limited_pct": 22.3,
            "unimproved_pct": 18.2,
            "surface_water_pct": 8.5
        },
        "water_stress_index": 0.58,
        "flood_risk_score": 0.18,
        "drought_risk_score": 0.55,
        "climate_vulnerability": 0.58,
        "infrastructure_gap": 0.52,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 550,
        "near_water_body": False,
        "coastal": False,
        "population_density": 35
    },
    {
        "id": "tz-mwanza",
        "name": "Mwanza Region",
        "country": "Tanzania",
        "region_type": "Lakeside",
        "coordinates": {"lat": -2.5, "lng": 33.0},
        "population": 3771826,
        "water_access": {
            "safely_managed_pct": 28.5,
            "basic_pct": 38.2,
            "limited_pct": 15.8,
            "unimproved_pct": 12.5,
            "surface_water_pct": 5.0
        },
        "water_stress_index": 0.35,
        "flood_risk_score": 0.38,
        "drought_risk_score": 0.28,
        "climate_vulnerability": 0.42,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1000,
        "near_water_body": True,
        "coastal": False,
        "population_density": 150
    },
    {
        "id": "tz-dar",
        "name": "Dar es Salaam",
        "country": "Tanzania",
        "region_type": "Urban Coastal",
        "coordinates": {"lat": -6.8, "lng": 39.3},
        "population": 6580177,
        "water_access": {
            "safely_managed_pct": 45.2,
            "basic_pct": 32.5,
            "limited_pct": 12.3,
            "unimproved_pct": 6.5,
            "surface_water_pct": 3.5
        },
        "water_stress_index": 0.52,
        "flood_risk_score": 0.55,
        "drought_risk_score": 0.25,
        "climate_vulnerability": 0.48,
        "infrastructure_gap": 0.35,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 1050,
        "near_water_body": True,
        "coastal": True,
        "population_density": 1780
    },
    {
        "id": "tz-mara",
        "name": "Mara Region",
        "country": "Tanzania",
        "region_type": "Lakeside",
        "coordinates": {"lat": -1.8, "lng": 34.0},
        "population": 2415448,
        "water_access": {
            "safely_managed_pct": 22.5,
            "basic_pct": 35.8,
            "limited_pct": 18.2,
            "unimproved_pct": 15.5,
            "surface_water_pct": 8.0
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.32,
        "drought_risk_score": 0.38,
        "climate_vulnerability": 0.48,
        "infrastructure_gap": 0.48,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 950,
        "near_water_body": True,
        "coastal": False,
        "population_density": 65
    },

    # Uganda
    {
        "id": "ug-karamoja",
        "name": "Karamoja Region",
        "country": "Uganda",
        "region_type": "Arid/Semi-arid",
        "coordinates": {"lat": 2.8, "lng": 34.5},
        "population": 1230515,
        "water_access": {
            "safely_managed_pct": 8.5,
            "basic_pct": 22.5,
            "limited_pct": 18.3,
            "unimproved_pct": 32.2,
            "surface_water_pct": 18.5
        },
        "water_stress_index": 0.78,
        "flood_risk_score": 0.12,
        "drought_risk_score": 0.85,
        "climate_vulnerability": 0.82,
        "infrastructure_gap": 0.85,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 350,
        "near_water_body": False,
        "coastal": False,
        "population_density": 25
    },
    {
        "id": "ug-central",
        "name": "Central Region",
        "country": "Uganda",
        "region_type": "Mixed",
        "coordinates": {"lat": 0.5, "lng": 32.5},
        "population": 10418804,
        "water_access": {
            "safely_managed_pct": 32.5,
            "basic_pct": 38.2,
            "limited_pct": 15.8,
            "unimproved_pct": 9.5,
            "surface_water_pct": 4.0
        },
        "water_stress_index": 0.38,
        "flood_risk_score": 0.42,
        "drought_risk_score": 0.28,
        "climate_vulnerability": 0.42,
        "infrastructure_gap": 0.38,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1250,
        "near_water_body": True,
        "coastal": False,
        "population_density": 200
    },

    # Ghana
    {
        "id": "gh-northern",
        "name": "Northern Region",
        "country": "Ghana",
        "region_type": "Semi-arid",
        "coordinates": {"lat": 9.5, "lng": -1.0},
        "population": 2947720,
        "water_access": {
            "safely_managed_pct": 15.2,
            "basic_pct": 32.5,
            "limited_pct": 22.3,
            "unimproved_pct": 20.0,
            "surface_water_pct": 10.0
        },
        "water_stress_index": 0.55,
        "flood_risk_score": 0.22,
        "drought_risk_score": 0.48,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.58,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 600,
        "near_water_body": False,
        "coastal": False,
        "population_density": 45
    },
    {
        "id": "gh-ashanti",
        "name": "Ashanti Region",
        "country": "Ghana",
        "region_type": "Forest",
        "coordinates": {"lat": 6.75, "lng": -1.5},
        "population": 5228508,
        "water_access": {
            "safely_managed_pct": 28.5,
            "basic_pct": 42.5,
            "limited_pct": 15.8,
            "unimproved_pct": 9.2,
            "surface_water_pct": 4.0
        },
        "water_stress_index": 0.35,
        "flood_risk_score": 0.38,
        "drought_risk_score": 0.22,
        "climate_vulnerability": 0.38,
        "infrastructure_gap": 0.35,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1400,
        "near_water_body": False,
        "coastal": False,
        "population_density": 180
    },
    {
        "id": "gh-greater-accra",
        "name": "Greater Accra Region",
        "country": "Ghana",
        "region_type": "Urban Coastal",
        "coordinates": {"lat": 5.75, "lng": -0.2},
        "population": 5455692,
        "water_access": {
            "safely_managed_pct": 48.5,
            "basic_pct": 32.5,
            "limited_pct": 10.2,
            "unimproved_pct": 5.8,
            "surface_water_pct": 3.0
        },
        "water_stress_index": 0.45,
        "flood_risk_score": 0.48,
        "drought_risk_score": 0.18,
        "climate_vulnerability": 0.42,
        "infrastructure_gap": 0.32,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 800,
        "near_water_body": True,
        "coastal": True,
        "population_density": 1200
    },

    # Niger
    {
        "id": "ne-diffa",
        "name": "Diffa Region",
        "country": "Niger",
        "region_type": "Arid",
        "coordinates": {"lat": 13.5, "lng": 13.0},
        "population": 593821,
        "water_access": {
            "safely_managed_pct": 5.2,
            "basic_pct": 15.8,
            "limited_pct": 18.5,
            "unimproved_pct": 35.5,
            "surface_water_pct": 25.0
        },
        "water_stress_index": 0.95,
        "flood_risk_score": 0.08,
        "drought_risk_score": 0.98,
        "climate_vulnerability": 0.98,
        "infrastructure_gap": 0.95,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 100,
        "near_water_body": True,
        "coastal": False,
        "population_density": 12
    },
    {
        "id": "ne-tahoua",
        "name": "Tahoua Region",
        "country": "Niger",
        "region_type": "Semi-arid",
        "coordinates": {"lat": 14.5, "lng": 5.0},
        "population": 3328365,
        "water_access": {
            "safely_managed_pct": 8.5,
            "basic_pct": 22.5,
            "limited_pct": 20.3,
            "unimproved_pct": 30.2,
            "surface_water_pct": 18.5
        },
        "water_stress_index": 0.85,
        "flood_risk_score": 0.12,
        "drought_risk_score": 0.88,
        "climate_vulnerability": 0.92,
        "infrastructure_gap": 0.88,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 250,
        "near_water_body": False,
        "coastal": False,
        "population_density": 25
    },

    # ==================== SOUTH ASIA ====================
    # Bangladesh
    {
        "id": "bd-dhaka",
        "name": "Dhaka Division",
        "country": "Bangladesh",
        "region_type": "Urban",
        "coordinates": {"lat": 23.8, "lng": 90.4},
        "population": 47332000,
        "water_access": {
            "safely_managed_pct": 38.5,
            "basic_pct": 42.5,
            "limited_pct": 10.2,
            "unimproved_pct": 5.8,
            "surface_water_pct": 3.0
        },
        "water_stress_index": 0.48,
        "flood_risk_score": 0.75,
        "drought_risk_score": 0.15,
        "climate_vulnerability": 0.62,
        "infrastructure_gap": 0.35,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2000,
        "near_water_body": True,
        "coastal": False,
        "population_density": 8500
    },
    {
        "id": "bd-chittagong",
        "name": "Chittagong Division",
        "country": "Bangladesh",
        "region_type": "Coastal",
        "coordinates": {"lat": 22.35, "lng": 91.8},
        "population": 33082000,
        "water_access": {
            "safely_managed_pct": 32.5,
            "basic_pct": 38.2,
            "limited_pct": 15.5,
            "unimproved_pct": 9.3,
            "surface_water_pct": 4.5
        },
        "water_stress_index": 0.38,
        "flood_risk_score": 0.82,
        "drought_risk_score": 0.12,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2800,
        "near_water_body": True,
        "coastal": True,
        "population_density": 850
    },
    {
        "id": "bd-sylhet",
        "name": "Sylhet Division",
        "country": "Bangladesh",
        "region_type": "Wetland",
        "coordinates": {"lat": 24.9, "lng": 91.9},
        "population": 11063000,
        "water_access": {
            "safely_managed_pct": 25.5,
            "basic_pct": 38.5,
            "limited_pct": 18.2,
            "unimproved_pct": 12.3,
            "surface_water_pct": 5.5
        },
        "water_stress_index": 0.25,
        "flood_risk_score": 0.92,
        "drought_risk_score": 0.05,
        "climate_vulnerability": 0.65,
        "infrastructure_gap": 0.48,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 3500,
        "near_water_body": True,
        "coastal": False,
        "population_density": 550
    },
    {
        "id": "bd-khulna",
        "name": "Khulna Division",
        "country": "Bangladesh",
        "region_type": "Delta",
        "coordinates": {"lat": 22.8, "lng": 89.5},
        "population": 16968000,
        "water_access": {
            "safely_managed_pct": 22.5,
            "basic_pct": 35.8,
            "limited_pct": 20.2,
            "unimproved_pct": 14.5,
            "surface_water_pct": 7.0
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.88,
        "drought_risk_score": 0.18,
        "climate_vulnerability": 0.78,
        "infrastructure_gap": 0.55,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 1800,
        "near_water_body": True,
        "coastal": True,
        "population_density": 520
    },
    {
        "id": "bd-rangpur",
        "name": "Rangpur Division",
        "country": "Bangladesh",
        "region_type": "Agricultural",
        "coordinates": {"lat": 25.75, "lng": 89.25},
        "population": 15878000,
        "water_access": {
            "safely_managed_pct": 28.5,
            "basic_pct": 38.2,
            "limited_pct": 18.5,
            "unimproved_pct": 10.3,
            "surface_water_pct": 4.5
        },
        "water_stress_index": 0.35,
        "flood_risk_score": 0.65,
        "drought_risk_score": 0.28,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.45,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2000,
        "near_water_body": False,
        "coastal": False,
        "population_density": 950
    },

    # India
    {
        "id": "in-rajasthan",
        "name": "Rajasthan",
        "country": "India",
        "region_type": "Arid",
        "coordinates": {"lat": 27.0, "lng": 74.0},
        "population": 68548437,
        "water_access": {
            "safely_managed_pct": 22.5,
            "basic_pct": 38.5,
            "limited_pct": 18.2,
            "unimproved_pct": 14.3,
            "surface_water_pct": 6.5
        },
        "water_stress_index": 0.75,
        "flood_risk_score": 0.12,
        "drought_risk_score": 0.72,
        "climate_vulnerability": 0.68,
        "infrastructure_gap": 0.48,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 300,
        "near_water_body": False,
        "coastal": False,
        "population_density": 200
    },
    {
        "id": "in-bihar",
        "name": "Bihar",
        "country": "India",
        "region_type": "Agricultural",
        "coordinates": {"lat": 25.5, "lng": 85.0},
        "population": 122912590,
        "water_access": {
            "safely_managed_pct": 18.5,
            "basic_pct": 35.2,
            "limited_pct": 22.5,
            "unimproved_pct": 16.3,
            "surface_water_pct": 7.5
        },
        "water_stress_index": 0.45,
        "flood_risk_score": 0.72,
        "drought_risk_score": 0.25,
        "climate_vulnerability": 0.58,
        "infrastructure_gap": 0.52,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1200,
        "near_water_body": True,
        "coastal": False,
        "population_density": 1100
    },
    {
        "id": "in-up",
        "name": "Uttar Pradesh",
        "country": "India",
        "region_type": "Agricultural",
        "coordinates": {"lat": 27.0, "lng": 80.0},
        "population": 231514939,
        "water_access": {
            "safely_managed_pct": 25.5,
            "basic_pct": 42.5,
            "limited_pct": 16.8,
            "unimproved_pct": 10.2,
            "surface_water_pct": 5.0
        },
        "water_stress_index": 0.52,
        "flood_risk_score": 0.48,
        "drought_risk_score": 0.32,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 900,
        "near_water_body": True,
        "coastal": False,
        "population_density": 828
    },
    {
        "id": "in-gujarat",
        "name": "Gujarat",
        "country": "India",
        "region_type": "Coastal Semi-arid",
        "coordinates": {"lat": 22.25, "lng": 71.25},
        "population": 70101458,
        "water_access": {
            "safely_managed_pct": 35.5,
            "basic_pct": 38.2,
            "limited_pct": 12.5,
            "unimproved_pct": 8.8,
            "surface_water_pct": 5.0
        },
        "water_stress_index": 0.65,
        "flood_risk_score": 0.35,
        "drought_risk_score": 0.55,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.38,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 600,
        "near_water_body": True,
        "coastal": True,
        "population_density": 310
    },
    {
        "id": "in-tamilnadu",
        "name": "Tamil Nadu",
        "country": "India",
        "region_type": "Coastal",
        "coordinates": {"lat": 11.0, "lng": 78.0},
        "population": 78101980,
        "water_access": {
            "safely_managed_pct": 42.5,
            "basic_pct": 38.5,
            "limited_pct": 10.2,
            "unimproved_pct": 5.8,
            "surface_water_pct": 3.0
        },
        "water_stress_index": 0.58,
        "flood_risk_score": 0.42,
        "drought_risk_score": 0.45,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.35,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 950,
        "near_water_body": True,
        "coastal": True,
        "population_density": 600
    },
    {
        "id": "in-delhi",
        "name": "Delhi NCR",
        "country": "India",
        "region_type": "Urban",
        "coordinates": {"lat": 28.6, "lng": 77.2},
        "population": 32041674,
        "water_access": {
            "safely_managed_pct": 55.5,
            "basic_pct": 32.5,
            "limited_pct": 7.5,
            "unimproved_pct": 3.0,
            "surface_water_pct": 1.5
        },
        "water_stress_index": 0.72,
        "flood_risk_score": 0.35,
        "drought_risk_score": 0.38,
        "climate_vulnerability": 0.42,
        "infrastructure_gap": 0.25,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 650,
        "near_water_body": True,
        "coastal": False,
        "population_density": 11297
    },

    # Pakistan
    {
        "id": "pk-sindh",
        "name": "Sindh Province",
        "country": "Pakistan",
        "region_type": "Semi-arid",
        "coordinates": {"lat": 25.0, "lng": 68.0},
        "population": 54883000,
        "water_access": {
            "safely_managed_pct": 28.5,
            "basic_pct": 35.2,
            "limited_pct": 16.5,
            "unimproved_pct": 12.3,
            "surface_water_pct": 7.5
        },
        "water_stress_index": 0.78,
        "flood_risk_score": 0.65,
        "drought_risk_score": 0.55,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.55,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 150,
        "near_water_body": True,
        "coastal": True,
        "population_density": 180
    },
    {
        "id": "pk-balochistan",
        "name": "Balochistan Province",
        "country": "Pakistan",
        "region_type": "Arid",
        "coordinates": {"lat": 28.5, "lng": 65.0},
        "population": 15036000,
        "water_access": {
            "safely_managed_pct": 12.5,
            "basic_pct": 28.5,
            "limited_pct": 22.3,
            "unimproved_pct": 24.2,
            "surface_water_pct": 12.5
        },
        "water_stress_index": 0.92,
        "flood_risk_score": 0.15,
        "drought_risk_score": 0.88,
        "climate_vulnerability": 0.85,
        "infrastructure_gap": 0.78,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 100,
        "near_water_body": False,
        "coastal": True,
        "population_density": 20
    },
    {
        "id": "pk-punjab",
        "name": "Punjab Province",
        "country": "Pakistan",
        "region_type": "Agricultural",
        "coordinates": {"lat": 31.0, "lng": 72.0},
        "population": 127688000,
        "water_access": {
            "safely_managed_pct": 38.5,
            "basic_pct": 38.2,
            "limited_pct": 12.5,
            "unimproved_pct": 7.3,
            "surface_water_pct": 3.5
        },
        "water_stress_index": 0.62,
        "flood_risk_score": 0.55,
        "drought_risk_score": 0.42,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.38,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 500,
        "near_water_body": True,
        "coastal": False,
        "population_density": 560
    },
    {
        "id": "pk-karachi",
        "name": "Karachi Division",
        "country": "Pakistan",
        "region_type": "Urban Coastal",
        "coordinates": {"lat": 24.85, "lng": 67.0},
        "population": 20711000,
        "water_access": {
            "safely_managed_pct": 42.5,
            "basic_pct": 35.5,
            "limited_pct": 12.2,
            "unimproved_pct": 6.8,
            "surface_water_pct": 3.0
        },
        "water_stress_index": 0.68,
        "flood_risk_score": 0.42,
        "drought_risk_score": 0.35,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.38,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 200,
        "near_water_body": True,
        "coastal": True,
        "population_density": 4500
    },

    # ==================== SOUTHEAST ASIA ====================
    # Indonesia
    {
        "id": "id-westjava",
        "name": "West Java Province",
        "country": "Indonesia",
        "region_type": "Dense Urban",
        "coordinates": {"lat": -6.5, "lng": 107.5},
        "population": 49355000,
        "water_access": {
            "safely_managed_pct": 45.5,
            "basic_pct": 35.2,
            "limited_pct": 10.5,
            "unimproved_pct": 5.8,
            "surface_water_pct": 3.0
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.62,
        "drought_risk_score": 0.18,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.32,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2500,
        "near_water_body": False,
        "coastal": True,
        "population_density": 1350
    },
    {
        "id": "id-eastjava",
        "name": "East Java Province",
        "country": "Indonesia",
        "region_type": "Mixed",
        "coordinates": {"lat": -7.5, "lng": 112.75},
        "population": 40835000,
        "water_access": {
            "safely_managed_pct": 38.5,
            "basic_pct": 38.5,
            "limited_pct": 12.5,
            "unimproved_pct": 7.5,
            "surface_water_pct": 3.0
        },
        "water_stress_index": 0.48,
        "flood_risk_score": 0.48,
        "drought_risk_score": 0.32,
        "climate_vulnerability": 0.48,
        "infrastructure_gap": 0.38,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2000,
        "near_water_body": True,
        "coastal": True,
        "population_density": 800
    },
    {
        "id": "id-nusa",
        "name": "Nusa Tenggara",
        "country": "Indonesia",
        "region_type": "Semi-arid",
        "coordinates": {"lat": -8.5, "lng": 120.0},
        "population": 5322092,
        "water_access": {
            "safely_managed_pct": 18.5,
            "basic_pct": 32.5,
            "limited_pct": 22.3,
            "unimproved_pct": 18.2,
            "surface_water_pct": 8.5
        },
        "water_stress_index": 0.72,
        "flood_risk_score": 0.22,
        "drought_risk_score": 0.68,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.62,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 800,
        "near_water_body": True,
        "coastal": True,
        "population_density": 110
    },
    {
        "id": "id-sulawesi",
        "name": "South Sulawesi Province",
        "country": "Indonesia",
        "region_type": "Coastal",
        "coordinates": {"lat": -4.0, "lng": 120.0},
        "population": 9073508,
        "water_access": {
            "safely_managed_pct": 28.5,
            "basic_pct": 38.2,
            "limited_pct": 18.5,
            "unimproved_pct": 10.3,
            "surface_water_pct": 4.5
        },
        "water_stress_index": 0.38,
        "flood_risk_score": 0.52,
        "drought_risk_score": 0.35,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.45,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2200,
        "near_water_body": True,
        "coastal": True,
        "population_density": 185
    },
    {
        "id": "id-papua",
        "name": "Papua Province",
        "country": "Indonesia",
        "region_type": "Remote",
        "coordinates": {"lat": -4.0, "lng": 138.0},
        "population": 4303707,
        "water_access": {
            "safely_managed_pct": 15.5,
            "basic_pct": 28.5,
            "limited_pct": 22.3,
            "unimproved_pct": 22.2,
            "surface_water_pct": 11.5
        },
        "water_stress_index": 0.35,
        "flood_risk_score": 0.58,
        "drought_risk_score": 0.25,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.82,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 3000,
        "near_water_body": True,
        "coastal": True,
        "population_density": 12
    },

    # Philippines
    {
        "id": "ph-manila",
        "name": "Metro Manila",
        "country": "Philippines",
        "region_type": "Urban",
        "coordinates": {"lat": 14.6, "lng": 121.0},
        "population": 13923452,
        "water_access": {
            "safely_managed_pct": 52.5,
            "basic_pct": 32.5,
            "limited_pct": 8.5,
            "unimproved_pct": 4.5,
            "surface_water_pct": 2.0
        },
        "water_stress_index": 0.48,
        "flood_risk_score": 0.72,
        "drought_risk_score": 0.18,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.28,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 2000,
        "near_water_body": True,
        "coastal": False,
        "population_density": 22000
    },
    {
        "id": "ph-cebu",
        "name": "Cebu Province",
        "country": "Philippines",
        "region_type": "Coastal Urban",
        "coordinates": {"lat": 10.3, "lng": 123.9},
        "population": 4925580,
        "water_access": {
            "safely_managed_pct": 38.5,
            "basic_pct": 38.2,
            "limited_pct": 12.5,
            "unimproved_pct": 7.3,
            "surface_water_pct": 3.5
        },
        "water_stress_index": 0.55,
        "flood_risk_score": 0.48,
        "drought_risk_score": 0.32,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 1700,
        "near_water_body": True,
        "coastal": True,
        "population_density": 750
    },
    {
        "id": "ph-davao",
        "name": "Davao Region",
        "country": "Philippines",
        "region_type": "Coastal",
        "coordinates": {"lat": 7.0, "lng": 125.5},
        "population": 5243500,
        "water_access": {
            "safely_managed_pct": 42.5,
            "basic_pct": 35.8,
            "limited_pct": 12.2,
            "unimproved_pct": 6.5,
            "surface_water_pct": 3.0
        },
        "water_stress_index": 0.38,
        "flood_risk_score": 0.52,
        "drought_risk_score": 0.28,
        "climate_vulnerability": 0.48,
        "infrastructure_gap": 0.38,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2000,
        "near_water_body": True,
        "coastal": True,
        "population_density": 300
    },
    {
        "id": "ph-bicol",
        "name": "Bicol Region",
        "country": "Philippines",
        "region_type": "Typhoon-prone",
        "coordinates": {"lat": 13.5, "lng": 123.0},
        "population": 6082428,
        "water_access": {
            "safely_managed_pct": 28.5,
            "basic_pct": 38.5,
            "limited_pct": 18.2,
            "unimproved_pct": 10.3,
            "surface_water_pct": 4.5
        },
        "water_stress_index": 0.32,
        "flood_risk_score": 0.85,
        "drought_risk_score": 0.15,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.52,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2800,
        "near_water_body": True,
        "coastal": True,
        "population_density": 320
    },

    # Vietnam
    {
        "id": "vn-hochiminh",
        "name": "Ho Chi Minh City",
        "country": "Vietnam",
        "region_type": "Urban",
        "coordinates": {"lat": 10.8, "lng": 106.7},
        "population": 9949436,
        "water_access": {
            "safely_managed_pct": 48.5,
            "basic_pct": 35.2,
            "limited_pct": 9.5,
            "unimproved_pct": 4.8,
            "surface_water_pct": 2.0
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.78,
        "drought_risk_score": 0.15,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.28,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 1900,
        "near_water_body": True,
        "coastal": True,
        "population_density": 4800
    },
    {
        "id": "vn-mekong",
        "name": "Mekong Delta",
        "country": "Vietnam",
        "region_type": "Delta",
        "coordinates": {"lat": 10.0, "lng": 105.8},
        "population": 17520000,
        "water_access": {
            "safely_managed_pct": 32.5,
            "basic_pct": 38.5,
            "limited_pct": 15.5,
            "unimproved_pct": 9.0,
            "surface_water_pct": 4.5
        },
        "water_stress_index": 0.28,
        "flood_risk_score": 0.88,
        "drought_risk_score": 0.25,
        "climate_vulnerability": 0.68,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1800,
        "near_water_body": True,
        "coastal": True,
        "population_density": 430
    },
    {
        "id": "vn-hanoi",
        "name": "Hanoi",
        "country": "Vietnam",
        "region_type": "Urban",
        "coordinates": {"lat": 21.0, "lng": 105.8},
        "population": 8246666,
        "water_access": {
            "safely_managed_pct": 52.5,
            "basic_pct": 32.5,
            "limited_pct": 8.5,
            "unimproved_pct": 4.5,
            "surface_water_pct": 2.0
        },
        "water_stress_index": 0.38,
        "flood_risk_score": 0.52,
        "drought_risk_score": 0.22,
        "climate_vulnerability": 0.42,
        "infrastructure_gap": 0.28,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 1650,
        "near_water_body": True,
        "coastal": False,
        "population_density": 2800
    },
    {
        "id": "vn-central",
        "name": "Central Highlands",
        "country": "Vietnam",
        "region_type": "Highland",
        "coordinates": {"lat": 12.5, "lng": 108.0},
        "population": 5632585,
        "water_access": {
            "safely_managed_pct": 22.5,
            "basic_pct": 35.8,
            "limited_pct": 20.2,
            "unimproved_pct": 15.3,
            "surface_water_pct": 6.2
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.35,
        "drought_risk_score": 0.45,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.52,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1600,
        "near_water_body": False,
        "coastal": False,
        "population_density": 110
    },

    # Cambodia
    {
        "id": "kh-phnompenh",
        "name": "Phnom Penh",
        "country": "Cambodia",
        "region_type": "Urban",
        "coordinates": {"lat": 11.55, "lng": 104.9},
        "population": 2288122,
        "water_access": {
            "safely_managed_pct": 45.5,
            "basic_pct": 38.5,
            "limited_pct": 9.5,
            "unimproved_pct": 4.5,
            "surface_water_pct": 2.0
        },
        "water_stress_index": 0.35,
        "flood_risk_score": 0.62,
        "drought_risk_score": 0.18,
        "climate_vulnerability": 0.48,
        "infrastructure_gap": 0.32,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1400,
        "near_water_body": True,
        "coastal": False,
        "population_density": 3500
    },
    {
        "id": "kh-tonle",
        "name": "Tonle Sap Region",
        "country": "Cambodia",
        "region_type": "Lakeside",
        "coordinates": {"lat": 12.5, "lng": 104.0},
        "population": 3500000,
        "water_access": {
            "safely_managed_pct": 18.5,
            "basic_pct": 32.5,
            "limited_pct": 22.3,
            "unimproved_pct": 18.2,
            "surface_water_pct": 8.5
        },
        "water_stress_index": 0.28,
        "flood_risk_score": 0.72,
        "drought_risk_score": 0.22,
        "climate_vulnerability": 0.55,
        "infrastructure_gap": 0.55,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 1500,
        "near_water_body": True,
        "coastal": False,
        "population_density": 75
    },

    # Myanmar
    {
        "id": "mm-yangon",
        "name": "Yangon Region",
        "country": "Myanmar",
        "region_type": "Urban Coastal",
        "coordinates": {"lat": 16.85, "lng": 96.15},
        "population": 7612439,
        "water_access": {
            "safely_managed_pct": 38.5,
            "basic_pct": 38.2,
            "limited_pct": 12.5,
            "unimproved_pct": 7.3,
            "surface_water_pct": 3.5
        },
        "water_stress_index": 0.42,
        "flood_risk_score": 0.58,
        "drought_risk_score": 0.22,
        "climate_vulnerability": 0.52,
        "infrastructure_gap": 0.42,
        "groundwater_potential": "high",
        "annual_rainfall_mm": 2700,
        "near_water_body": True,
        "coastal": True,
        "population_density": 850
    },
    {
        "id": "mm-rakhine",
        "name": "Rakhine State",
        "country": "Myanmar",
        "region_type": "Coastal",
        "coordinates": {"lat": 19.5, "lng": 93.5},
        "population": 3188807,
        "water_access": {
            "safely_managed_pct": 18.5,
            "basic_pct": 32.5,
            "limited_pct": 22.3,
            "unimproved_pct": 18.2,
            "surface_water_pct": 8.5
        },
        "water_stress_index": 0.38,
        "flood_risk_score": 0.72,
        "drought_risk_score": 0.18,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.68,
        "groundwater_potential": "moderate",
        "annual_rainfall_mm": 3200,
        "near_water_body": True,
        "coastal": True,
        "population_density": 85
    },
    {
        "id": "mm-dry",
        "name": "Dry Zone (Mandalay)",
        "country": "Myanmar",
        "region_type": "Arid",
        "coordinates": {"lat": 22.0, "lng": 96.0},
        "population": 8232000,
        "water_access": {
            "safely_managed_pct": 15.5,
            "basic_pct": 28.5,
            "limited_pct": 22.5,
            "unimproved_pct": 22.5,
            "surface_water_pct": 11.0
        },
        "water_stress_index": 0.78,
        "flood_risk_score": 0.15,
        "drought_risk_score": 0.72,
        "climate_vulnerability": 0.72,
        "infrastructure_gap": 0.62,
        "groundwater_potential": "low",
        "annual_rainfall_mm": 500,
        "near_water_body": True,
        "coastal": False,
        "population_density": 150
    },
]

# Cost benchmarks from World Bank/UNICEF data
COST_BENCHMARKS = {
    "borehole": {
        "min_cost": 15000,
        "max_cost": 50000,
        "min_population_served": 500,
        "max_population_served": 2000,
        "cost_per_capita_range": (10, 30),
        "maintenance_annual_pct": 0.05,
        "lifespan_years": 20
    },
    "rainwater_harvesting": {
        "min_cost_per_household": 50,
        "max_cost_per_household": 200,
        "avg_household_size": 5,
        "maintenance_annual_pct": 0.03,
        "lifespan_years": 15
    },
    "surface_water_treatment": {
        "min_cost": 100000,
        "max_cost": 500000,
        "min_population_served": 5000,
        "max_population_served": 50000,
        "cost_per_capita_range": (10, 25),
        "maintenance_annual_pct": 0.08,
        "lifespan_years": 25
    },
    "managed_aquifer_recharge": {
        "min_cost": 50000,
        "max_cost": 200000,
        "min_population_served": 2000,
        "max_population_served": 20000,
        "cost_per_capita_range": (10, 40),
        "maintenance_annual_pct": 0.04,
        "lifespan_years": 30
    },
    "piped_water_extension": {
        "cost_per_meter_min": 50,
        "cost_per_meter_max": 150,
        "connection_cost_min": 50,
        "connection_cost_max": 200,
        "maintenance_annual_pct": 0.06,
        "lifespan_years": 40
    },
    "desalination": {
        "cost_per_cubic_meter_min": 0.50,
        "cost_per_cubic_meter_max": 2.00,
        "capital_cost_per_m3_day": 1000,  # Daily capacity
        "min_population_served": 10000,
        "maintenance_annual_pct": 0.10,
        "lifespan_years": 20
    }
}

# Intervention types with suitability criteria
INTERVENTION_TYPES = {
    "borehole": {
        "name": "Borehole/Groundwater Wells",
        "description": "Deep wells accessing groundwater aquifers",
        "suitable_conditions": {
            "groundwater_potential": ["high", "moderate"],
            "max_flood_risk": 0.4,
            "min_drought_risk": None,
            "coastal_eligible": True,
            "population_density_range": (10, 500)
        },
        "water_yield_liters_per_day": 5000,
        "reliability_score": 0.85
    },
    "rainwater_harvesting": {
        "name": "Rainwater Harvesting Systems",
        "description": "Collection and storage of rainwater for domestic use",
        "suitable_conditions": {
            "min_annual_rainfall": 400,
            "max_population_served": 1000,
            "community_size_range": (50, 500),
            "coastal_eligible": True
        },
        "water_yield_liters_per_mm_rain": 0.8,
        "reliability_score": 0.65
    },
    "surface_water_treatment": {
        "name": "Surface Water Treatment",
        "description": "Treatment of water from rivers, lakes, or reservoirs",
        "suitable_conditions": {
            "requires_water_body": True,
            "max_water_stress": 0.6,
            "min_population": 1000,
            "coastal_eligible": True
        },
        "water_yield_liters_per_day": 50000,
        "reliability_score": 0.90
    },
    "managed_aquifer_recharge": {
        "name": "Managed Aquifer Recharge (MAR)",
        "description": "Storing flood water underground for later use",
        "suitable_conditions": {
            "min_flood_risk": 0.5,
            "groundwater_potential": ["high", "moderate"],
            "min_annual_rainfall": 600,
            "coastal_eligible": True
        },
        "water_yield_liters_per_day": 20000,
        "reliability_score": 0.75
    },
    "piped_water_extension": {
        "name": "Piped Water Extension",
        "description": "Extending existing piped water networks",
        "suitable_conditions": {
            "min_safely_managed_pct": 30,
            "min_population_density": 200,
            "max_infrastructure_gap": 0.5,
            "coastal_eligible": True
        },
        "water_yield_liters_per_day": 100000,
        "reliability_score": 0.95
    },
    "desalination": {
        "name": "Desalination Plant",
        "description": "Converting seawater to freshwater",
        "suitable_conditions": {
            "requires_coastal": True,
            "min_water_stress": 0.5,
            "min_population": 50000,
            "groundwater_potential": ["low", "moderate"]
        },
        "water_yield_liters_per_day": 100000,
        "reliability_score": 0.92
    }
}
